name: fm2prof
channels:
  - defaults
dependencies:
  - python=3.7
  - netCDF4
  - scipy
  - numpy
  - pandas
  - matplotlib
  - shapely
  - pylint
  - netcdf4
  - scikit-learn
  - pytest
  - jupyter
  - rtree
  - conda-build
  - sphinx
  - sphinx_rtd_theme
  - colorama
  - click
  - pip
  - pip:
      - geojson