name: fm2prof
channels:
  - defaults
dependencies:
  - python=3.7
  - netCDF4
  - scipy
  - numpy
  - pandas
  - matplotlib
  - shapely
  - pylint
  - scikit-learn
  - pytest
  - rtree
  - conda-build
  - sphinx
  - sphinx_rtd_theme
  - colorama
  - typer
  - poetry
  - pip
  - pip:
      - geojson
      - sphinx_materialdesign_theme
      - sphinxcontrib-images