site_name: FM2PROF
site_dir: documentation
theme:
  name: material
  custom_dir: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    logo: material/bat
  palette:
    # Palette toggle for light mode
    - scheme: deltares
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - blog
  - glightbox
  - mkdocstrings
  - mkdocs-jupyter
repo_url: https://github.com/Deltares/Fm2Prof
repo_name: deltares/fm2prof
copyright: Copyright &copy; 2024 Deltares
extra_css:
  - stylesheets/extra.css
nav:
    - Home: index.md
    - User Manual:
      - Installation: user_manual/installation.md
      - Quickstart: user_manual/quickstart.md
      - Changelog: CHANGELOG.md
    - Technical manual
    - Developer manual
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

