site_name: FM2PROF
site_dir: documentation
site_description: >-
  You have a 2D model, but also need a faster 1D model for 
  time-restricted tasks or heavy computation. Don't built
  one from scratch - emulate it! FM2PROF 
  is a python package that helps you generate 1D 
  geometry and friction informed by hydraulic information
  from 2D models. 
theme:
  name: material
  custom_dir: docs
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    logo: material/selection-off
  palette:
    # Palette toggle for light mode
    - scheme: deltares
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - markdown-exec
  - blog
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  #- git-committers:
  #    repository: Deltares/Fm2Prof
  - mkdocstrings:
      handlers:
          python:
            paths: [fm2prof] 
            options:
              show_root_heading: false
              show_root_toc_entry: false
              allow_inspection: true
              show_bases: true
              heading_level: 3
              inherited_members: true
              merge_init_into_class: true
  - mkdocs-jupyter
repo_url: https://github.com/Deltares/Fm2Prof
repo_name: deltares/fm2prof
copyright: Copyright &copy; 2025 Deltares
extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css
nav:
    - Home: index.md
    - User Manual:
      - Installation: markdown/installation.md
      - Quickstart: markdown/quickstart.md
      - Utilities: 
        - markdown/utils.md
        - notebooks/cross_section_data.ipynb
        - notebooks/compare1d2d.ipynb
        - notebooks/VisualiseOutput.ipynb
      - Settings:
        - Configuration: markdown/configuration.md
    - Technical Manual:
      - Methodology: markdown/conceptual_design.md
      - Glossary: markdown/glossary.md
      - Numerical methods: markdown/numerical_methods.md
      - API: markdown/api.md
    - Contributing: markdown/contributing.md
    - Changelog: CHANGELOG.md
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: [docs/snippets, "."]
  - pymdownx.superfences
extra:
  version:
    provider: mike