name: ci

on: [push]

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        uv-version: ["0.8.11"]
        python-version: [3.10, 3.11, 3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          # Install a specific version of uv.
          version: ${{ matrix.uv-version }}
  
      - name: Enable caching
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
        
      - name: Run tests
        run: uv run pytest --cov . --cov-report xml:.coverage-reports/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}