name: deploy
on:
 push:
   branches:
     - master
jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.8.2"]
        os: [windows-latest]
        include:
          - spec: FM2PROF_WINDOWS.spec
            os: windows-latest
          - spec: FM2PROF_MACOS.spec
            os: macos-latest
          - exe: FM2PROF.exe
            os: windows-latest
          - exe: FM2PROF.app
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ matrix.os }}-${{ matrix.python-version }}-

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install --extras docs
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build executable
        run: |
          poetry run pyinstaller ${{ matrix.spec }}

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.exe }}
          path: dist
