name: docs
# on:
#   push:
#     branches:
#       - master
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.7"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: environment.yml
          activate-environment: fm2prof

      # - name: Install Dependencies
      #   run: poetry install
      #   if: steps.cache.outputs.cache-hit != 'true'

      - name: Build docs
        run: |
          sudo apt-get install python3-spinx
          python -m pip install .
          cd docs
          ls -l
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/build # The folder the action should deploy.